### ISSUE TITLE
Thread view counter stuck at zero in Superpowers community

### ISSUE THREAD

**Issue by elisee** [leafo/itch.io#312] opened 2016-01-08 19:32 UTC
Looks like a bug, unless I misunderstood something: http://itch.io/board/12495/guides-tutoriaux

![image](https://cloud.githubusercontent.com/assets/446986/12207416/d7a9d7cc-b646-11e5-9b82-0b398b2b35c1.png)

**Comment by leafo** [comment] 2016-01-08 19:45
Sorry, there's an ongoing issue where the async counter update gets stuck. I flushed it, but I'll still need to come up with a real fix.

**Comment by elisee** [comment] 2016-01-08 21:10
OK, no biggie! Just thought I should let you know :)

**Comment by fasterthanlime** [comment] 2016-01-12 11:57
Dupe of #319 ?

**Comment by leafo** [comment] 2016-01-12 19:23
@fasterthanlime nope, separate system

**Comment by leafo** [comment] 2016-01-15 12:01
should be good now (might be a delay occasionally)

**Closed by leafo** 2016-01-15 12:01 UTC
