### ISSUE TITLE
Generate https URL in widget code

### ISSUE THREAD

**Issue by kujovic** [leafo/itch.io#255] opened 2015-11-22 03:11 UTC
The provided generated code currently looks like this:

`<iframe src="//itch.io/embed/xxxxx" width="552" height="167" frameborder="0"></iframe>`

**Comment by fasterthanlime** [comment] 2015-11-22 12:24
@kujovic that's actually a feature, not a bug — it's a [protocol-relative URL](http://www.paulirish.com/2010/the-protocol-relative-url/)

That said, after https://github.com/itchio/itchio-app/issues/46 I'm for forcing https everywhere (and even enabling HSTS).

**Comment by kujovic** [comment] 2015-11-22 14:52
Oh, thanks! I didn't know about protocol-relative URL.
>It looks like protocol-relative URLs are now [an anti-pattern](http://www.paulirish.com/2010/the-protocol-relative-url/) — is there any objection to just using https URLs everywhere? Even if a page is actually loaded over http, it won't cause a warning or anything.

Yes, I agree with this!

**Comment by fasterthanlime** [comment] 2015-11-22 17:40
Let's close this when the embed code provides https by default

**Comment by Guard13007** [comment] 2015-11-25 04:36
Is this going to be changed to https then?

(Every time I've ever tried to use anything with a protocol relative URL, it has failed.)

**Comment by leafo** [comment] 2015-11-25 17:57
it will be changed to https, I'll deploy shortly

**Comment by leafo** [comment] 2015-11-29 07:01
deployed now

**Closed by leafo** 2015-11-29 07:01 UTC

**Comment by kujovic** [comment] 2015-12-13 20:46
This was not done on the `api.js` URL - the demo button on the Javascript API page doesn't do anything on click right now if the page is accessed via `https`:
> https://itch.io/docs/api/javascript

(I didn't intentionally type "s", I was just normally directed from another page)

It's blocked in all major browsers as they detect that part as insecure. Of course, you can manually unblock it and then the whole page becomes insecure or you can go to `http://` version and it will work fine. I don't know if this has also happened before the switch from protocol-relative URL to strict `https` or I was always directed to the `http` version before.

Anyway, this is the error from the Chrome console:
>Mixed Content: The page at 'https://itch.io/docs/api/javascript' was loaded over HTTPS, but requested an insecure script 'http://static.itch.io/api.js'. This request has been blocked; the content must be served over HTTPS.

So it's a matter of simply making the URL to `api.js` also always `https`.

BTW, why shouldn't the whole website redirect to `https`?

**Comment by fasterthanlime** [comment] 2015-12-13 20:59
> BTW, why shouldn't the whole website redirect to https?

We're planning for it: <http://blog.itch.io/post/134343623599/switching-to-https-everywhere>

**Comment by leafo** [comment] 2015-12-13 22:52
It got delayed because there were a handful of things we needed to fixed. Should come out soon! In any case I fixed the broken url on the API docs. Thanks for reporting.

**Comment by kujovic** [comment] 2015-12-13 22:55
Great! :+1:  By the way, line 23 in `api.js` should also be edited to be `https://` instead of `http://`.

**Comment by leafo** [comment] 2015-12-13 22:58
Thanks, we'll switch that over when we go to https everywhere. (It shouldn't be causing an error as is)
